export const languageCodes = [
  { id: 1, label: "Spanish (United States)", value: "es-US" },
  { id: 2, label: "Urdu (Pakistan)", value: "ur-PK" },
  { id: 3, label: "English (United Kingdom)", value: "en-GB" },
  { id: 4, label: "Hindi (India)", value: "hi-IN" },
  { id: 5, label: "Kannada (India)", value: "kn-IN" },
  { id: 6, label: "Russian (Russia)", value: "ru-RU" },
  { id: 7, label: "Dutch (Netherlands)", value: "nl-NL" },
  { id: 8, label: "Italian (Italy)", value: "it-IT" },
  { id: 9, label: "Assamese (India)", value: "as-IN" },
  { id: 10, label: "Vietnamese (Vietnam)", value: "vi-VN" },
  { id: 11, label: "Ukrainian (Ukraine)", value: "uk-UA" },
  { id: 12, label: "Swedish (Sweden)", value: "sv-SE" },
  { id: 13, label: "Chinese (Traditional, Taiwan)", value: "zh-TW" },
  { id: 14, label: "English (United States)", value: "en-US" },
  { id: 15, label: "German (Germany)", value: "de-DE" },
  { id: 16, label: "Cantonese (Hong Kong)", value: "yue-HK" },
  { id: 17, label: "Welsh (United Kingdom)", value: "cy-GB" },
  { id: 18, label: "Polish (Poland)", value: "pl-PL" },
  { id: 19, label: "English (Australia)", value: "en-AU" },
  { id: 20, label: "French (Canada)", value: "fr-CA" },
  { id: 21, label: "Danish (Denmark)", value: "da-DK" },
  { id: 22, label: "Bengali (Bangladesh)", value: "bn-BD" },
  { id: 23, label: "Telugu (India)", value: "te-IN" },
  { id: 24, label: "Croatian (Croatia)", value: "hr-HR" },
  { id: 25, label: "English (India)", value: "en-IN" },
  { id: 26, label: "Meitei/Manipuri (India)", value: "mni-IN" },
  { id: 27, label: "Indonesian (Indonesia)", value: "in-ID" },
  { id: 28, label: "Chinese (Simplified, China)", value: "zh-CN" },
  { id: 29, label: "Malayalam (India)", value: "ml-IN" },
  { id: 30, label: "Hebrew (Israel)", value: "iw-IL" },
  { id: 31, label: "Turkish (Turkey)", value: "tr-TR" },
  { id: 32, label: "French (France)", value: "fr-FR" },
  { id: 33, label: "Arabic", value: "ar" },
  { id: 34, label: "Estonian (Estonia)", value: "et-EE" },
  { id: 35, label: "Dogri (India)", value: "doi-IN" },
  { id: 36, label: "Malay (Malaysia)", value: "ms-MY" },
  { id: 37, label: "Bosnian (Bosnia and Herzegovina)", value: "bs-BA" },
  { id: 38, label: "Javanese (Indonesia)", value: "jv-ID" },
  { id: 39, label: "Korean (South Korea)", value: "ko-KR" },
  { id: 40, label: "Greek (Greece)", value: "el-GR" },
  { id: 41, label: "Santali (India)", value: "sat-IN" },
  { id: 42, label: "Filipino (Philippines)", value: "fil-PH" },
  { id: 43, label: "Bengali (India)", value: "bn-IN" },
  { id: 44, label: "Finnish (Finland)", value: "fi-FI" },
  { id: 45, label: "Hungarian (Hungary)", value: "hu-HU" },
  { id: 46, label: "Sinhala (Sri Lanka)", value: "si-LK" },
  { id: 47, label: "Slovak (Slovakia)", value: "sk-SK" },
  { id: 48, label: "Bulgarian (Bulgaria)", value: "bg-BG" },
  { id: 49, label: "Thai (Thailand)", value: "th-TH" },
  { id: 50, label: "Khmer (Cambodia)", value: "km-KH" },
  { id: 51, label: "Punjabi (India)", value: "pa-IN" },
  { id: 52, label: "Portuguese (Portugal)", value: "pt-PT" },
  { id: 53, label: "Czech (Czech Republic)", value: "cs-CZ" },
  { id: 54, label: "Spanish (Spain)", value: "es-ES" },
  { id: 55, label: "Swahili (Kenya)", value: "sw-KE" },
  { id: 56, label: "Gujarati (India)", value: "gu-IN" },
  { id: 57, label: "Icelandic (Iceland)", value: "is-IS" },
  { id: 58, label: "Catalan (Spain)", value: "ca-ES" },
  { id: 59, label: "Norwegian Bokmål (Norway)", value: "nb-NO" },
  { id: 60, label: "Tamil (India)", value: "ta-IN" },
  { id: 61, label: "Serbian (Serbia)", value: "sr-RS" },
  { id: 62, label: "Odia (India)", value: "or-IN" },
  { id: 63, label: "Portuguese (Brazil)", value: "pt-BR" },
  { id: 64, label: "Dutch/Flemish (Belgium)", value: "nl-BE" },
  { id: 65, label: "Bodo (India)", value: "brx-IN" },
  { id: 66, label: "Sundanese (Indonesia)", value: "su-ID" },
  { id: 67, label: "Japanese (Japan)", value: "ja-JP" },
  { id: 68, label: "Kashmiri (India)", value: "ks-IN" },
  { id: 69, label: "Latvian (Latvia)", value: "lv-LV" },
  { id: 70, label: "Marathi (India)", value: "mr-IN" },
  { id: 71, label: "English (Nigeria)", value: "en-NG" },
  { id: 72, label: "Albanian (Albania)", value: "sq-AL" },
  { id: 73, label: "Maithili (India)", value: "mai-IN" },
  { id: 74, label: "Lithuanian (Lithuania)", value: "lt-LT" },
  { id: 75, label: "Sanskrit (India)", value: "sa-IN" },
  { id: 76, label: "Sindhi (India)", value: "sd-IN" },
  { id: 77, label: "Romanian (Romania)", value: "ro-RO" },
  { id: 78, label: "Konkani (India)", value: "kok-IN" },
  { id: 79, label: "Nepali (Nepal)", value: "ne-NP" },
];
